railway.data = read.csv('Rail_Data.csv')
install.packages('dplyr')
library(dplyr)
glimpse(railway.data)
mydata <- railway.data
wss <- (nrow(mydata)-1)*sum(apply(mydata,2,var))
for(i in 2:15) wss[i] <- sum(kmeans(mydata, centers = i)$withinss)
plot(1:15, wss, type = "b", xlab = "Numbers of clusters", ylab = "Within groups sum of squares", col="green", pch =12)
install.packages("vegan")
library(vegan)
fit <- cascadeKM(scale(railway.data, center = TRUE, scale = TRUE),1, 15, iter = 1000)
plot(fit, sortg = TRUE, grpmts.plot = TRUE)
calinski.best <- as.numeric(which.max(fit$results[2,]))
cat("Calinski criterion optimal number of clusters: ", calinski.best, "\n")
fit <- kmeans(mydata, 6)
railway.data$cluster <- fit$cluster
View(railway.data)
library(ggplot2)
ggplot(railway.data, aes(Train.Number, Passenger.Kilometers, color = as.factor(cluster))) +geom_point()
